-- 코드를 입력하세요
SELECT U1.TITLE, U1.BOARD_ID, U2.REPLY_ID, U2.WRITER_ID, U2.CONTENTS, DATE_FORMAT(U2.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD U1 JOIN USED_GOODS_REPLY U2
ON U1.BOARD_ID = U2.BOARD_ID
WHERE DATE_FORMAT(U1.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY U2.CREATED_DATE ASC, U1.TITLE ASC;